### ISSUE TITLE
Assess current design patterns and make a to-do list

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1082]
In order to see a high-level view of the styles used to build the prototype, and to prepare for creating a more consistent, efficient design system from them, we'll conduct an audit of what we have going on, then identify next steps from what we learn. 

### to-do list (that will turn into subsequent issues):
 - [x] Conduct an audit (see the work!)
 - [x] Synthesize findings (figure out what the work is)
 - [x] Make new issues for identified areas (break up the work into smaller actionable chunks)

**Comment by jenniferthibault** [comment]
I've been collecting the styles and patterns in [this Mural](https://app.mural.co/t/gsa6/m/gsa6/1541519041265/08088a073981788567ca9b9edb33412f672144a3), which has some notes as I went along. 

Next going to organize them by level of disruption or how much they slow down making design decisions.  👀 @hbillings

**Comment by jenniferthibault** [comment]
## Actions identified
Here's a starter list of things we should consider addressing, ordered by things that are most disruptive to wireframing/styling work. Would love Heather's additions or re-orders because there's definitely different use cases for front end.

### Build a more helpful grid system
- [ ] Implement a grid that has built-in margins between columns so that we can eliminate excess left/right markup. 
    - [ ] Set screen breakpoints at specific px sizes instead of ems

### Limit/standardize the number of spacing increments
- [ ] Define the spacing measurements we need in pattern applications (especially top/bottom increments). Right now seems like there's many in use and it's a bit arbitrary

### Simplify button styles, and don't use buttons for things that don't initiate actions
 - [ ] Reduce the number of button styles  to `primary`, `secondary`, and `call-to-action` and decide how each should be styled. Then, apply correct instances of each button in the app
    - [ ] Change some buttons to links
    - [ ] Use secondary button style for withdraw interaction
- [ ] Change yes/no buttons to radio selects with conditional text input

### Make form layouts more consistent between sections
- [ ] Standardize how headings / labels are laid out for shorter text inputs
- [ ] Set consistent widths for text areas (in increment variables appropriate to the amount of content)

### Alerts / messages
- Create consistent styles for `success` `warning` and `error` validation styles. (These should visually be related to the help text styles)

**Comment by NAretakis** [comment]
This all looks great to me. :+1:

**Comment by hbillings** [comment]
Of the list here, my priorities for the front end would be:

Grid
Form layout
Alerts/messages
Spacing
Buttons

I'd also add:
Font sizes
Colors

IMO, the things that will be most important to iron out immediately are:
Grid
Form layout
Alerts/messages

**Comment by jenniferthibault** [comment]
I think this is ready to close in favor of moving into the smaller issues, but will wait for other folks to chime in since the update last Friday was a big one.

**Comment by hbillings** [comment]
This looks good to me! I think we can focus on prioritizing the related issues.

**Comment by jenniferthibault** [comment]
Closing in favor of the smaller issues

**Comment by nkkl** [comment]
>We’d like help prioritizing the remaining items in a way that makes sense in context of the rest of the project’s goals. I’ll get started on at least making issues for the ones that don’t have them yet, (which probably makes this issue "done" 🎉 ) but will hold off on adding them to the board or adding labels so that you can help with that prioritizing.

@NAretakis @jeromeleecms I think it would be a good idea to meet with Jen about these prior to sprint planning (if possible) so that we can get the right things into the next sprint.
