### ISSUE TITLE
Design print preview functionality that streamlines export functionality

### ISSUE THREAD

**Issue by NAretakis** [18F/cms-hitech-apd#1160]
From #974, we need to make the print preview button hide "Helptext" and "Reminders" when displaying APD in print previous mode. By hiding these elements, we'll be left with a consolidated single APD view, that can be printed to PDF, and/or exported to docx (maybe).

It would also be nice to make sure the print previous has:

- [x] Helptext and Reminders removed from display (#1349)
- [ ] not too large font size for print ~size 12
- [ ] reduced whitespace and section outlines to consolidate the view
- [x] tables that fit within the view (without having to scroll) — #1394 will solve this one!
- [x] buttons removed from view (#1348 + 1375)
- [x] section headers and titles remain - to provide context the content
- [ ] probably other things?
 
This issue is complete when:
- [ ] Devs know what needs to be done to meet this need (by either making smaller issues, or delivering redlines, etc.)

**Comment by jenniferthibault** [comment]
This feels more like dev than design to me — switching the labels!

**Comment by jenniferthibault** [comment]
Update: In grooming we determined I was wrong about it being a dev issue. Updated the criteria and description above!

**Comment by NAretakis** [comment]
This might close-able?

**Comment by jenniferthibault** [comment]
When @jeromeleecms @hbillings @nkkl and I talked on Friday, we identified one lingering set of tables as the main blocker for this layer: **[The Proposed Budget Tables](https://hitech-apd.app.cloud.gov/apd#budget)**

These tables are too wide, too complex, and have items that are hidden until a user interacts with them, which makes them hidden from print. Boo.

## Old (left) vs Updated (right)
- Uses the same method we've been using throughout to split up the grouped tables by year and type
- This takes up more vertical space, but is completely viewable on one screen, and be more printable.
- Restyles the expandable table cell to match the table formatting AND splits up the content by FFY (just like the rest of the table)
- On print, the cells would print in expanded state (is this possible??)

This table is a MONSTER. So here's a 🖼 [full page view in InVision](https://gsa.invisionapp.com/d/main/#/console/16805703/352925179/preview). It's not clickable, but it shows how tables are broken up. 

![Screen Shot 2019-03-18 at 9 55 18 PM](https://user-images.githubusercontent.com/11636908/54574961-b9bd7980-49c8-11e9-8379-024f112de71c.png)

![Screen Shot 2019-03-18 at 9 58 54 PM](https://user-images.githubusercontent.com/11636908/54575078-2afd2c80-49c9-11e9-840f-1292f36c5c33.png)

@hbillings let's talk about this tomorrow!

**Comment by lauraponce** [comment]
Created #1394 for the development of the updated table styles

**Comment by lauraponce** [comment]
@hbillings @mgwalker I'm trying to think through ways to reduce the unnecessary whitespace in the print preview — for the PDF, is it possible to reduce the size of the text boxes and scale to fit the text that's in them? Or is that not worth the effort of solving for the pilot?

**Comment by mgwalker** [comment]
I don't know about scaling the text boxes (CSS; who even knows?), but another option might be to have the text boxes hidden in print, and a corresponding set of `<div>`s or `<p>`s that show the text box content and are hidden on screen.  Basically just swap element types.

**Comment by hbillings** [comment]
@mgwalker I like that idea (though I'm worried that it might negatively impact performance somehow). This seems to be how the rich text editor boxes behave already; there are a number of old JS tricks to get `textarea`s to expand to fit their contents while someone's typing (or `onBlur`) that we could apply to other `textarea`s..

**Comment by lauraponce** [comment]
We have some time reserved on 4/11 to talk through this more! ✔️

**Comment by CSwartzHMA** [comment]
I am not available on 4/11 however, we have the following feedback items that seem to fit with this issue to add to the conversation:

The print preview takes a very long time to load - more noticeably in Chrome than in IE. Chrome also errored saying page became unresponsive.
Budget tables are misaligned and not formatted. 
Section breaks cross pages.
In IE on the APD we tested, pages 70-125 were blank, but no content was missing. The content was condensed but the remaining pages were left on the print preview.
Comparison of export of same APD - Chrome file size = 5828 mb vs IE 684.
Size 7 font noted for actual APD content (not headers, etc.)

**Comment by lauraponce** [comment]
Created #1441 to address these concerns and to clean up the print layout. Closing this out!
