### ISSUE TITLE
Set up end of milestone presentation for project sponsors

### ISSUE THREAD

**Issue by nkkl** [18F/cms-hitech-apd#132]
We should share out our work to our sponsors, so that they can see what we're doing and give us feedback! Milestone 2 ends February 23, so sometime around then would be ideal. An hour is probably fine.

### This task is done when...
 - [x] Sam can come
 - [x] Carrie can come
 - [x] Eugene can come
 - [x] Eghosa can come

**Comment by NAretakis** [comment]
Meeting scheduled for 2/28/18
