### ISSUE TITLE
All the tickets related to Program Activities / Section 4 

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1450]
Here is a collection of all the Program Activities (Section 4) tickets.

- [ ] 4: Program activities section: https://github.com/18F/cms-hitech-apd/issues/1450 
- [x] 4.1.0: Review pattern for section: https://github.com/18F/cms-hitech-apd/issues/1561
- [x] 4.1.1: Activity List: https://github.com/18F/cms-hitech-apd/issues/1501
- [x] 4.2: Activity Overview: https://github.com/18F/cms-hitech-apd/issues/1452
- [x] 4.3: Performance Goals and Benchmarks https://github.com/18F/cms-hitech-apd/issues/1453
- [x] 4.4: Activity Schedule https://github.com/18F/cms-hitech-apd/issues/1455
- [x] 4.5: In-House Cost Categories (personnel and non-personnel) https://github.com/18F/cms-hitech-apd/issues/1456
- [x] 4.6: Private Contractor Costs https://github.com/18F/cms-hitech-apd/issues/1522
- [x] 4.7: Cost Allocation: https://github.com/18F/cms-hitech-apd/issues/1526
- [x] 4.8: Standards & Conditions https://github.com/18F/cms-hitech-apd/issues/1523

![4_Program Activities FINAL](https://user-images.githubusercontent.com/23194720/58506632-d65ef600-815d-11e9-8c2b-6f9fa7617a72.png)

**Comment by austinhernandez** [comment]
Here is a collection of all the Program Activities (Section 4) tickets.

4: Program activities section: https://github.com/18F/cms-hitech-apd/issues/1450 
4.1: Activity List: https://github.com/18F/cms-hitech-apd/issues/1501
4.2: Activity Overview: https://github.com/18F/cms-hitech-apd/issues/1452
4.3: Performance Goals and Benchmarks https://github.com/18F/cms-hitech-apd/issues/1453
4.4: Activity Schedule https://github.com/18F/cms-hitech-apd/issues/1455
4.5: In-House Cost Categories (personnel and non-personnel) https://github.com/18F/cms-hitech-apd/issues/1456
4.6: Private Contractor Costs https://github.com/18F/cms-hitech-apd/issues/1522
4.7: Cost Allocation: https://github.com/18F/cms-hitech-apd/issues/1526
4.8: Standards & Conditions https://github.com/18F/cms-hitech-apd/issues/1523

**Comment by austinhernandez** [comment]
The whole thing (except for every single thing in the Standards & Conditions section cuz that was a lot of copy and paste, but you get the idea of format).
![4_Program Activities FINAL](https://user-images.githubusercontent.com/23194720/58503484-b6780400-8156-11e9-8be5-951431490947.png)

**Comment by mgwalker** [comment]
I believe this one is done - all of the linked issues have been closed.  😄
