### ISSUE TITLE
Replace date picker and use review pattern for milestones in Activity Schedule subsection (Program Activities subsection), and make consistent with design system

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1455]
Within the Program Activities section, the 3rd subsection is Activity Schedule. This subsection currently uses the calendar picker, but there is no calendar component in the CMS design system and they recommend using the date field instead. The date field here is using the blue line pattern from the checkboxes/radio buttons with children.
![image](https://user-images.githubusercontent.com/23194720/58211046-ce640980-7cb8-11e9-8838-fae917a37910.png)
![image](https://user-images.githubusercontent.com/23194720/58211122-0f5c1e00-7cb9-11e9-88a8-7cceb6d35626.png)

### This task is done when...
 - [x] `Activity Schedule` is `h4.ds-h4`
 - [ ] `Activity start and end dates` and `Milestones` labels are `h5.ds-h5`
 - [ ] Date entry boxes have been swapped out for a new multi-box format
 - [ ] List of milestones uses the review pattern for adding, editing, and removing milestones
 - [ ] Milestone titles are `h6.ds-h4` (semantically smaller but visually larger)
 - [ ] There is an `hr` at the bottom of the section

**Comment by austinhernandez** [comment]
Here is a mockup of this section:
![image](https://user-images.githubusercontent.com/23194720/58211046-ce640980-7cb8-11e9-8838-fae917a37910.png)
![image](https://user-images.githubusercontent.com/23194720/58210959-98268a00-7cb8-11e9-9c7b-6be0770b045d.png)

Please use the implemented styles from the design system and lmk if you have questions!
