### ISSUE TITLE
The Epic Pilot

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1591]
Things we will need to accomplish during the pilot and during the wind down of the pilot

### This task is done when...
 - [x] Pilot has started
 - [x] Related Issues in the Pilot have been completed
- [x] Pilot has been completed and next steps have been determined
 
*Add a LABEL (design, dev, compliance, BUG, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

**Comment by jeromeleecms** [comment]
Closing this out per Team Discussion.
