### ISSUE TITLE
ARIA-live regions are read aloud when the app loads, even when there's not been a change

### ISSUE THREAD

**Issue by hbillings** [18F/cms-hitech-apd#1616]
In an incredibly amusi-nnoying twist, trying to use ARIA-live regions for input tables results in those numbers being read first thing when a user loads the app. A whole bunch of numbers without context isn't useful for anyone. 

UPDATE: It's not just the numbers in the table; one of our design system components and our date validation tags are also culprits.

### This task is done when...
 - [x] The app no longer announces random dollar amounts when loaded, but also provides a logical way to update users on totals that change with their input (#1731)
 - [x] The app no longer scolds you for date validation on page load (#1742)
 - [ ] The app no longer shouts "NO" at you on page load (#1743)

**Comment by mgwalker** [comment]
![no no no no](https://media.giphy.com/media/l378h4fviW00hcm88/giphy.gif)

**Comment by jeromeleecms** [comment]
Closed out in favor of tracking #1742 and #1743 individually.
