### ISSUE TITLE
508 Compliance Work to Scale Beyond Pilot

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1628]
This Epic captures all the 508 Compliance work that will be done during and after the Pilot to ensure we can scale the APD builder portion of the eAPD beyond the four selected states. This is also required under the waiver we received from the CMS 508 testing team.

### This task is done when...
 - [ ] 508 Compliance Work is Completed (internal team)
 - [ ] 508 Compliance Work has been submitted to testing (external testing)
- [ ] 508 Compliance Remediation Completed (internal team)
- [ ] 508 Compliance completed (external testing validation)
 
*Add a LABEL (design, dev, compliance, BUG, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

**Comment by jeromeleecms** [comment]
Closing this as it has no tasks associated with it and has been lingering for too long.
