### ISSUE TITLE
Test the new activity UI and content with users

### ISSUE THREAD

**Issue by lauraponce** [18F/cms-hitech-apd#1813]
To see if the UI refinements and content updates from #1790 are a better UX for users, we will should do some usability testing.

### This task is done when...
 - [ ] Create research plan
 - [ ] Put together the concepts for testing
 - [ ] Recruit participants
 - [ ] Conduct testing
 - [ ] Synthesize feedback
 - [ ] Share out findings
 - [ ] Document next steps and create new GitHub issues

**Comment by lauraponce** [comment]
Starting to draft up the research plan here: https://docs.google.com/document/d/1fAyb8GK5kcg6yeekfaEJnN5Q2bjKtwV7y5VK4hIND5E/edit#

**Comment by lauraponce** [comment]
Closing in favor of #1855
