### ISSUE TITLE
Transition Current Data Model (Relational) to Document Model

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#1825]
Transitioning to the Document Model will enable a faster implementation of future features. 

### This task is done when...
 - [ ] API's updated to support document model
 - [ ] App creates APDs based on document model
- [ ] App has been migrated to document model

**Comment by jeromeleecms** [comment]
Closing this epic in favor of more focused epics. @mgwalker will spin this up.
