### ISSUE TITLE
Add API endpoints for managing users and user roles

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#208]
Manage roles:
- [x] view list of activities - #225
- [x] view list of roles - #203
- [x] create roles - #223
- [x] modify activities of an existing role - #216
- [x] delete role - #226

Manage users:
- [x] view list of users - #63
- [x] create users - #63
- [x] modify role of an existing user
- [x] delete user
