### ISSUE TITLE
ATO Authorization

### ISSUE THREAD

**Issue by nicholeweems** [18F/cms-hitech-apd#2239]
This Epic captures all ATO efforts that will be completed to ensure MACPro-eAPD’s builder meets ATO’s requirements necessary to go live in production supporting all US states and territories.

### This task is done when...
 - [ ] ATO efforts are completed (internal MACPro-eAPD team)
 - [ ] ATO documentation and ancillary support has been submitted for review (CMS ATO Team)
 - [ ] ATO vulnerability remediation is completed (internal MACPro-eAPD team)
 - [ ] ATO authorization is approved (CMS ATO Team)
