### ISSUE TITLE
Update project README or other documentation

### ISSUE THREAD

**Issue by mgwalker** [18F/cms-hitech-apd#45]
- document authentication
  - [ ] passport configuration, etc. (#30)
  - [ ] API endpoints (#33)
  - [ ] authorization model (#32)
  - [ ] ~~token (#35)~~ authentication (see #47)

- document how the web app works
  - [ ] how routing works (#28)
  - [ ] how app state management works (#27)
  - [ ] how the app hits the API (#29)
  - [ ] how we're doing CSS (#34)

**Comment by mgwalker** [comment]
For documenting API endpoints, what if we just wrote some Swagger?  I've got some code somewhere that conditionally enables CORS based on a Swagger spec, too, which might be pretty handy.

**Comment by brendansudol** [comment]
I like idea of Swagger if it makes our lives easier

**Comment by brendansudol** [comment]
I'm marking this as complete (with https://github.com/18F/cms-hitech-apd/pull/64 now merged); @mgwalker, if need be, let's open smaller issues for other documentation holes
