### ISSUE TITLE
Backend Development Complete for APD Creation and Submission Experience

### ISSUE THREAD

**Issue by jeromeleecms** [18F/cms-hitech-apd#714]
To wrap up the APD Creation and Submission Experience milestone, we would like to verify that the backend portion of the experience is complete. This will mirror #577 which captured the front end experience.

This verifies that all CRUD (create, read, update, delete) + other functionality id'd by Dev is working + documentation complete.

Let me know if this is too detailed or not detailed enough.

cc: @NAretakis @nkkl 

### This task is done when...

**New APD can be created**
- [x] APD Created

**State Profile Contact Information**

- [x] Medicaid Director information 

 **Program Summary**

- [x] Program Introduction 
- [x] HIT Overview information 
- [x] HIE Overview information
- [x] MMIS Overview information

**Results of Previous Activities**

- [x] Prior Activities Summary
- [x] Actual Expenses

**Program Activities**

- [x] Program Administration Information
- [x] Needs and Objectives 
- [x] Activity Schedule 
- [x] Personnel
- [x] Contract Resources
- [x] Non Personnel Costs
- [x] Cost Allocation
- [x] Standards and Conditions

**Proposed Budget**
- [x] Summary Budget Table (#727)
- [x] Federal Share by FFY Quarter (#727)
- [x] Incentive Payment By FFY Quarter (#727)

**Assurances and Compliance**
- [x] Federal Citations and Justification (#713)

**Executive Summary**
- [x] Executive Summary (#727)
- [x] Program Budget Table (#727)

**Certify and Submit**
- [x] APD Is stored

**Comment by mgwalker** [comment]
**Proposed Budget**
- Summary budget table is not stored, it's calculated live
  - we've talked about storing the fully-computed table when the APD is submitted, so it's searchable but also so if the calculations ever change, past APDs won't be affected

**Executive Summary**
- Executive summary is derived from other contents and not stored
- Program budget table is not stored, it's calculated live
  - should we store these when the APD is submitted too?  it would make sense, for the same reasons as above

**Comment by mgwalker** [comment]
The way it's implemented right now, there are two APD tables - one is editable (while the APD is in draft status) where states build their drafts, and the other is for submission snapshots and is not editable.  It sounds like you want us to compute all the computed values and store in the snapshots - that makes sense to me.  So ideally, the snapshot is 100% complete - nothing needs to be computed anymore, and it contains exactly the numbers that the state saw when they submitted it?

I think for pre-populating an update, using either the draft table or the snapshot table is fine since once an APD is approved, the final snapshot should have all the same info as the draft.  We already have most of the code to create a new draft from an existing one, too.

**Comment by NAretakis** [comment]
I like all of this. Snapshot is 100% complete, and matches the numbers the state saw when they submitted. Update approach makes sense too, it looks like we have options to ether use the snapshot or the computing version, and we can just see what works better.

**Comment by jeromeleecms** [comment]
@mgwalker I saw #727 and #713 close out thanks to heroic efforts by @brendansudol -- ready to close?

**Comment by mgwalker** [comment]
Nearly!  Need to resolve the conflicts between different pieces of work and then it'll be good to go.

**Comment by jeromeleecms** [comment]
Done!
